title: George Balla # your name (or website title) here
logo: "/images/george_pic.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, Machine Learning Engineer 
  <br><br>
  Project Engineering, Manufacturing Automation, IOT
  <br><br>
  <a href="https://www.linkedin.com/in/george-balla/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-S4CE38VRDM # your Google Analytics tracking ID here
